Repository RAF-SI-2024/Banka-4-Mobile, pull requests merged in 2025-03, with the labels that each got.

#2 *: add editorconfig
  .editorconfig
Labels: approved, size/S, lgtm

#14 feature/totp screen
  android-app/app/src/main/java/rs/raf/rafeisen/model/TotpSecret.kt
  android-app/app/src/main/java/rs/raf/rafeisen/navigation/AppNavigation.kt
  android-app/app/src/main/java/rs/raf/rafeisen/screen/totp/AddTotpContract.kt
  android-app/app/src/main/java/rs/raf/rafeisen/screen/totp/AddTotpScreen.kt
  android-app/app/src/main/java/rs/raf/rafeisen/screen/totp/AddTotpViewModel.kt
  android-app/app/src/main/java/rs/raf/rafeisen/screen/totp/TotpContract.kt
  android-app/app/src/main/java/rs/raf/rafeisen/screen/totp/TotpScreen.kt
  android-app/app/src/main/java/rs/raf/rafeisen/screen/totp/TotpViewModel.kt
Labels: lgtm, size/L

#22 android: fix linter and formatter not being configured
  android-app/app/build.gradle.kts
Labels: approved, size/S
